### ISSUE TITLE
Problem with video format

### ISSUE THREAD

**Issue by no-e-in** [InfernoCycle/YouTubeDownloader#3]
I tried to download this [video](https://www.youtube.com/watch?v=-Z6SMQFYsvs) with type mp4 and audio format 'regular' and video format 480 (I tried all 3 options that the search provided). Unfortunately the video is not shown

**Comment by InfernoCycle** [comment]
I'm so sorry I just realized I forgot to add a "+" symbol in my code so only the audio format is downloaded when choosing only a custom video option. I will send out a fixed version soon. 

Choosing two different formats or just the defaults work from what i've tested just now. Sorry about that.

The coding mistake btw:

Missing a '+': `id2 + "[vcodec*="+vcodec+"]"+"ba/bv+ba"`

What it should of been: `id2 + "[vcodec*="+vcodec+"]"+"+ba/bv+ba"`

**Comment by no-e-in** [comment]
I tried the new version. This time only 2 codecs at 480 appeared: the first 'av01.0.04m.08 - 397' completed the download after a few seconds with an incorrect result; the second codec 'avc1.4d401e - 135' completed the download of both audio and video with correct result.

**Comment by InfernoCycle** [comment]
Thank You for telling me!!! This is usually a common problem due to YouTube having so many formats and yt-dl not knowing which format will work on a user's media player. I'll make another version today.  **I recommend only using the codecs that start with "avc"** which is the one that worked for you if it's available. I wouldn't use "**av0**" since it has been known to cause problems unless you have the codec support for it.
